---
- name: Add apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 93C4A3FD7BB9C367

- name: Add ubuntu trusty ppa per official installation recommendations
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main'
    state: present
    filename: ansible

- name: Install Ansible.
  apt: name=ansible state=present update_cache=yes
